Hijr/Hijr/Controllers/PertanyaanMaklumatController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Hijr.Controllers
{
    public class PertanyaanMaklumatController : Controller
    {
        // GET: PertanyaaMaklumat
        public ActionResult Index()
        {
            return View();
        }
    }
}

Hijr/Hijr/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - HIJR</title>
    <link rel="icon" href="~/img/th-small-logo.png" />
    @Styles.Render("~/Content/css")
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
    <style>
        .disabled{
    pointer-events:none;
    opacity:0.4;
}
    </style>
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-default  navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @*@Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })*@
                <img src="~/img/th-logo-1.png" alt="" />
                
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    
                    <li class="dropdown messages-menu" >
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">@*Korporat*@
                        </a>
                        @*<ul class="dropdown-menu" role="menu">
                            <li>
                                @Html.ActionLink("User Management", "Index", "UserManagement")
                            </li>
                            <li>
                                @Html.ActionLink("Customer Information", "Index", "Customer")
                            </li>
                            <li class="divider"></li>
                            <li><a href="#">Example of Separated link</a></li>
                        </ul>*@
                    </li>
                    <li><a href="#">@*Simpanan*@</a></li>
                    <li><a href="#">@*Haji*@</a></li>
                    <li><a href="#">@*Pelaburan*@</a></li>
                </ul>
                @*@Html.Partial("_LoginPartial")*@
            </div>
            <div class="jumbotron">
                <span class="text-success"><h2>HIJR</h2></span>
            </div>
            <div class="navbar-collapse navbar-hijr collapse">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="#" id="pertanyaanmaklumat" class="hijr_menu" data-rel="div_pertanyaan">Pertanyaan Maklumat JH</a>
                        @*@Html.ActionLink("Pertanyaan Maklumat JH", "Index", "PertanyaanMaklumat")*@
                    </li>
                    @*<li>@Html.ActionLink("Home", "Index", "Home")</li>*@
                    <li class="dropdown messages-menu">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" >
                            Tawaran
                        </a>
                        <ul class="dropdown-menu" role="menu" >
                            <li>
                               
                                <a href="#" id="pertanyaan" class="hijr_menu" data-rel="div_pertanyaan">Pertanyaan Surat Tawaran</a>
                            </li>
                            <li>
                                <a href="#" id="paparsurat" class="hijr_menu" data-rel="div_paparsurat">Papar Surat Tawaran</a>
                            </li>
                            <li>
                                <a href="#" id="pengesahan" class="hijr_menu" data-rel="div_pengesahan">Pengesahan</a>
                            </li>
                            <li>
                                <a href="#" id="ecard" class="hijr_menu" data-rel="div_ecard">Isu e-Card</a>
                            </li>
                            <li class="divider"></li>
                            <li><a href="#">Example of Separated link</a></li>
                        </ul>
                    </li>
                    <li class="dropdown messages-menu"><a href="#" class="dropdown-toggle" data-toggle="dropdown">Kursus</a>
                        <ul class="dropdown-menu" role="menu">
                            <li>
                                <a href="#" id="kursus" class="hijr_menu" data-rel="div_kursuskehadiran">Kemaskini Kehadiran</a>
                            </li>
                        </ul>
                    </li>
                    <li class="dropdown messages-menu"><a href="#" class="dropdown-toggle" data-toggle="dropdown">Kesihatan</a>
                        <ul class="dropdown-menu" role="menu">
                            <li>
                                <a href="#" id="kesihatanpengesahan" class="hijr_menu" data-rel="div_kesihatanpengesahan">Pengesahan</a>
                            </li>
                        </ul>
                    </li>
                    <li class="dropdown messages-menu"><a href="#" class="dropdown-toggle" data-toggle="dropdown">Passport/Visa</a>
                        <ul class="dropdown-menu" role="menu">
                            <li>
                                <a href="#" id="passportpenerimaan" class="hijr_menu" data-rel="div_passportpenerimaan">Penerimaan</a>
                            </li>
                            <li>
                                <a href="#" id="passportpenyerahan" class="hijr_menu" data-rel="div_passportpenyerahan">Penyerahan</a>
                            </li>
                            <li>
                                <a href="#" id="passportbagasi" class="hijr_menu" data-rel="div_passportbagasi">Bagasi</a>
                            </li>
                        </ul>
                    </li>
                    <li class="dropdown messages-menu">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Daftar Masuk</a>
                        <ul class="dropdown-menu" role="menu">
                            <li>
                                <a href="#" id="daftarkelanajaya" class="hijr_menu" data-rel="div_daftarkelanajaya">Kelana Jaya</a>
                            </li>
                            <li>
                                <a href="#" id="daftarhotel" class="hijr_menu" data-rel="div_daftarhotel">Hotel</a>
                            </li>
                        </ul>
                    </li>
                    <li><a href="#">Maklumat</a></li>
                    @*<li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>*@
                </ul>
               
        </div>
        
    </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year-Tabung Haji</p>
        </footer>
        <div class="modaluniversal"><!-- Place at bottom of page --></div>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>